#!/usr/bin/env python3
"""LLM-generated test cases for graphify verify.

When a function has complex param types (structs, interfaces) that can't be
auto-generated by testing/quick, this module asks the LLM to generate meaningful
test inputs based on:
  1. The function's signature and source code
  2. Real usage examples extracted from graph.json (call sites that pass real values)

The LLM produces Go literal expressions that construct valid inputs, which are
then used as curated test cases in the differential test harness.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional


def extract_call_sites_from_graph(graph_json: Path, function_name: str, limit: int = 3) -> list[str]:
    """Find real call sites of a function in graph.json and return the surrounding source context.

    Returns a list of source code snippets showing how the function is called.
    """
    if not graph_json.exists():
        return []

    data = json.loads(graph_json.read_text(encoding="utf-8"))
    nodes = data.get("nodes", [])
    edges = data.get("links", [])

    # Find the function's node ID
    func_nodes = [n for n in nodes if n.get("label") == function_name or n.get("label", "").endswith(f".{function_name}")]
    if not func_nodes:
        return []

    # Find callers (edges where target is the function)
    caller_ids = set()
    for edge in edges:
        if edge.get("relation") in ("calls", "indirect_call"):
            for fn in func_nodes:
                if edge.get("target") == fn.get("id"):
                    caller_ids.add(edge.get("source", ""))
                    if len(caller_ids) >= limit * 2:
                        break

    # Resolve caller IDs to source files
    call_sites = []
    for caller_id in list(caller_ids)[:limit * 2]:
        caller_node = next((n for n in nodes if n.get("id") == caller_id), None)
        if caller_node and caller_node.get("source_file"):
            src_file = caller_node.get("source_file")
            src_line = caller_node.get("source_location", "").lstrip("L")
            call_sites.append(f"{src_file}:{src_line} in {caller_node.get('label')}")
        if len(call_sites) >= limit:
            break

    return call_sites


def generate_llm_test_cases(
    function_name: str,
    function_source: str,
    param_types: list[str],
    call_sites: list[str],
    num_cases: int = 5,
) -> list[str]:
    """Ask the LLM to generate Go literal expressions for test inputs.

    Returns a list of strings, each being a comma-separated list of Go expressions
    that construct valid arguments for the function.
    """
    prompt = f"""You are a Go test input generator. I need you to generate {num_cases} test input
cases for a Go function. Each case should be a comma-separated list of Go literal expressions
that construct valid arguments matching the function's parameter types.

Function: {function_name}
Parameter types: {", ".join(param_types)}

Function source:
```go
{function_source[:1500]}
```

Real call sites in the codebase:
{chr(10).join(call_sites) if call_sites else "(none found)"}

Generate {num_cases} diverse test cases. Each case should be a single line containing
comma-separated Go expressions. Use realistic values based on the function's purpose.
For struct types, use `&TypeName{{Field: value}}` syntax. For basic types, use literals.

Output ONLY the {num_cases} lines, one per test case, no explanation, no code fences.
Example format for a function taking (string, int):
"hello", 42
"", 0
"test@example.com", -1

Generate the {num_cases} test cases now:"""

    try:
        result = subprocess.run(
            ["z-ai", "chat", "-p", prompt],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode != 0:
            return []

        out = result.stdout
        # Extract the content from the z-ai JSON response
        try:
            start = out.index("{")
            end = out.rindex("}") + 1
            data = json.loads(out[start:end])
            content = data["choices"][0]["message"]["content"].strip()
        except (json.JSONDecodeError, KeyError, IndexError, ValueError):
            return []

        # Parse the content — each non-empty line is a test case
        cases = []
        for line in content.split("\n"):
            line = line.strip()
            # Skip code fence markers
            if line.startswith("```") or line.startswith("//") or not line:
                continue
            # Strip leading/trailing quotes if the whole line is quoted
            if line.startswith('"') and line.endswith('"') and line.count('"') == 2:
                line = line[1:-1]
            cases.append(line)
            if len(cases) >= num_cases:
                break

        return cases
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return []


def generate_llm_test_cases_ts(
    function_name: str,
    function_source: str,
    param_types: list[str],
    call_sites: list[str],
    num_cases: int = 5,
) -> list[str]:
    """Ask the LLM to generate TypeScript test inputs."""
    prompt = f"""You are a TypeScript test input generator. Generate {num_cases} test input
cases for a TypeScript function. Each case should be a comma-separated list of TS expressions
that construct valid arguments.

Function: {function_name}
Parameter types: {", ".join(param_types)}

Function source:
```typescript
{function_source[:1500]}
```

Real call sites:
{chr(10).join(call_sites) if call_sites else "(none found)"}

Generate {num_cases} diverse test cases. Each case = one line with comma-separated TS expressions.
Use realistic values. For objects, use `{{ field: value }}` syntax.

Output ONLY the {num_cases} lines, no explanation, no code fences.

Generate the {num_cases} test cases now:"""

    try:
        result = subprocess.run(
            ["z-ai", "chat", "-p", prompt],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode != 0:
            return []
        out = result.stdout
        try:
            start = out.index("{")
            end = out.rindex("}") + 1
            data = json.loads(out[start:end])
            content = data["choices"][0]["message"]["content"].strip()
        except (json.JSONDecodeError, KeyError, IndexError, ValueError):
            return []

        cases = []
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("```") or line.startswith("//") or not line:
                continue
            cases.append(line)
            if len(cases) >= num_cases:
                break
        return cases
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return []


if __name__ == "__main__":
    # Quick test
    cases = generate_llm_test_cases(
        "ParseEncryptionKey",
        'func ParseEncryptionKey(hexKey string) ([]byte, error) {\n\tif hexKey == "" {\n\t\treturn nil, nil\n\t}\n\tkey, err := hex.DecodeString(hexKey)\n\tif err != nil {\n\t\treturn nil, fmt.Errorf("invalid hex key: %w", err)\n\t}\n\tif len(key) != 32 {\n\t\treturn nil, fmt.Errorf("key must be 32 bytes")\n\t}\n\treturn key, nil\n}',
        ["string"],
        [],
        num_cases=3,
    )
    for i, c in enumerate(cases, 1):
        print(f"Case {i}: {c}")
